### ISSUE TITLE
Failed to load libssl

### ISSUE THREAD

**Issue by Jonathan-Racaud** [thibmo/Beef-Net#1] opened 2021-11-28 16:32 UTC
Hi!, I'm trying to use your Beef-Net library and play/experiment with it, but I'm facing the following issue: **Failed to load shared library: libssl-1_1.dll**.

I did followed your install instructions and installed in the BeefLibs both Beef-Net and Beef-OpenSSL. Both projects are part of the workspace and added as dependencies for my project.

The libssl-1_1.dll is present in the built directory of the project.

Here's the compile output:
```
Compiling...
Beef compilation time: 0.02s
Executing Command: CopyToDependents("$(ProjectDir)/dist/OpenSSL/Win64/bin/*.dll")
Compile-to-debug time: 0.15s
Debugger started
Total build time: 0.15s
Loading PDB d:\Projects\ExperimentServer\build\Debug_Win64\ExperimentServer\ExperimentServer.pdb
Loading DLL: ntdll.dll @ 0x7FFA'E3A40000
Loading DLL: C:\WINDOWS\System32\KERNEL32.DLL @ 0x7FFA'E2410000
Loading DLL: C:\WINDOWS\System32\KERNELBASE.dll @ 0x7FFA'E1550000
Loading DLL: C:\WINDOWS\SYSTEM32\apphelp.dll @ 0x7FFA'DAF70000
Creating thread 21996
Creating thread 9756
Loading DLL: C:\WINDOWS\System32\USER32.dll @ 0x7FFA'E1E10000
Loading DLL: C:\WINDOWS\System32\win32u.dll @ 0x7FFA'E1520000
Loading DLL: C:\WINDOWS\SYSTEM32\VERSION.dll @ 0x7FFA'D64A0000
Creating thread 17900
Loading DLL: C:\WINDOWS\SYSTEM32\NETAPI32.dll @ 0x7FFA'C54F0000
Loading DLL: C:\WINDOWS\System32\GDI32.dll @ 0x7FFA'E1980000
Loading DLL: C:\WINDOWS\System32\msvcrt.dll @ 0x7FFA'E29C0000
Loading DLL: C:\WINDOWS\System32\msvcrt.dll @ 0x21A'0DAC0000
Unloading DLL: C:\WINDOWS\System32\msvcrt.dll @ 0x21A'0DAC0000
Loading DLL: C:\WINDOWS\System32\gdi32full.dll @ 0x7FFA'E10C0000
Loading DLL: C:\WINDOWS\System32\msvcp_win.dll @ 0x7FFA'E11E0000
Loading DLL: C:\WINDOWS\System32\ucrtbase.dll @ 0x7FFA'E0F20000
Loading DLL: C:\WINDOWS\System32\ADVAPI32.dll @ 0x7FFA'E3630000
Loading DLL: C:\WINDOWS\System32\sechost.dll @ 0x7FFA'E3420000
Loading DLL: C:\WINDOWS\System32\RPCRT4.dll @ 0x7FFA'E3500000
Loading DLL: d:\Projects\ExperimentServer\build\Debug_Win64\ExperimentServer\Beef042RT64.dll @ 0x7FFA'89740000
Loading DLL: d:\Projects\ExperimentServer\build\Debug_Win64\ExperimentServer\Beef042Dbg64.dll @ 0x7FFA'6D670000
Loading DLL: C:\WINDOWS\SYSTEM32\NETUTILS.DLL @ 0x7FFA'DFC30000
Loading DLL: C:\WINDOWS\System32\COMDLG32.dll @ 0x7FFA'E2A90000
Loading DLL: C:\WINDOWS\System32\SHELL32.dll @ 0x7FFA'E2C70000
Loading DLL: C:\WINDOWS\System32\combase.dll @ 0x7FFA'E1A20000
Loading DLL: C:\WINDOWS\System32\ole32.dll @ 0x7FFA'E3860000
Loading DLL: C:\WINDOWS\System32\shcore.dll @ 0x7FFA'E2B80000
Loading DLL: C:\WINDOWS\System32\SHLWAPI.dll @ 0x7FFA'E24D0000
Loading DLL: C:\WINDOWS\SYSTEM32\WINMM.dll @ 0x7FFA'D1BF0000
Loading DLL: C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e\COMCTL32.dll @ 0x7FFA'BD6F0000
Loading DLL: C:\WINDOWS\System32\IMM32.DLL @ 0x7FFA'E34C0000
Loading DLL: C:\WINDOWS\SYSTEM32\kernel.appcore.dll @ 0x7FFA'E0110000
Loading DLL: C:\WINDOWS\System32\bcryptPrimitives.dll @ 0x7FFA'E1040000
Loading DLL: C:\WINDOWS\system32\uxtheme.dll @ 0x7FFA'DB070000
Loading DLL: C:\ProgramData\A-Volute\A-Volute.SonicStudio3\Modules\ScheduledModules\x64\AudioDevProps2.dll @ 0x7FFA'A59D0000
Loading DLL: C:\WINDOWS\System32\WS2_32.dll @ 0x7FFA'E1DA0000
Setting SEH filter 00007FF7674EB5A0
Loading DLL: d:\Projects\ExperimentServer\build\Debug_Win64\ExperimentServer\libcrypto-1_1.dll @ 0x7FFA'5B340000
Loading DLL: C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll @ 0x7FFA'C53F0000
Loading DLL: C:\WINDOWS\SYSTEM32\bcrypt.dll @ 0x7FFA'E0900000
ERROR: Failed to load shared library: libssl-1_1.dll
Loading DLL: d:\Projects\ExperimentServer\build\Debug_Win64\ExperimentServer\libssl-1_1.dll @ 0x7FFA'812B0000
Unloading DLL: d:\Projects\ExperimentServer\build\Debug_Win64\ExperimentServer\libssl-1_1.dll @ 0x7FFA'812B0000
```

**Comment by LauraRozier** [comment] 2021-11-29 17:36
That's interesting, I'll have a look on a VM.
Perhaps I should also add a release package with all the unnecessary things stripped out, that way it's easier to install.

**Comment by LauraRozier** [comment] 2021-11-29 19:11
I can indeed repro the issue.
After a bunch of trail&error the issue is amazingly childish. :)
The error is that the DLLs are missing "-x64" in the name...

Fix incoming. :)

**Comment by LauraRozier** [comment] 2021-11-29 19:37
Fixed in commit 
8712ade

**Closed as completed by LauraRozier** 2021-11-29 19:37 UTC
Labels: bug
